### ISSUE TITLE
Relative URLs are translated into global URL pointing to source language translation

### ISSUE THREAD

**Issue by macin** [NetaliDev/dokuwiki-deepl-autotranslate#13]
Hi, I love the plugin but there is one very annoying thing - when I do translations, the plugin converts relative links to global links, and what's worse, it does it incorrectly, by pointing the new links to original namespace from which the translation was triggered. Would it be possible to fix this reasonably quickly as I have to translate to a new language my whole documentation portal.

**Comment by NetaliDev** [comment]
The plugin only converts links to global links, if the referenced page in the destination language-namespace does not exist yet.

So when you ensure that the referenced pages also exist in the destination language-namespace, the links should stay relative.

**Comment by macin** [comment]
Thanks @NetaliDev ... What is the reasoning behind such behavior? Would it be possible to extend the plugin, so the setting would control this behavior? I love the plugin but such behavior is causing a lot of additional work when we translate to the new language. Or maybe there is a way I could create language namespaces before hitting translate button which would be easy and straight forward, but I am not aware of. Could you please let me know how the efficient translation process should look like if this is intended behavior?  

From my perspective, doing nothing to the url's would be just perfect.

**Comment by NetaliDev** [comment]
I can add an option to disable this feature. I will try to add it this week.

**Comment by macin** [comment]
Excellent! Thank you Jenny!

**Comment by macin** [comment]
Hi @NetaliDev
Just wanted to check how things are going. If you need any help with testing I can offer my support :)

**Comment by NetaliDev** [comment]
Thanks to @splitbrain that should be fixed now with PR #14
