### ISSUE TITLE
Minor Bug: Table adjustments get lost

### ISSUE THREAD

**Issue by extrasec** [NetaliDev/dokuwiki-deepl-autotranslate#4]
Hi,

great plugin. I am flashed it works so smart.

I found a minor bug: When you have a double space at the beginning of a table cell to have the content aligned right the double space is converted to a singel space and destroys the alignment when there is content to be translated within the cell.

As alignment (i.e. of numbers) is often important for layout and ability to have a feeling for dimensions. In my case I present a combination of two spaces at the beginning of the cell, followed by a text and ending with a number. The number aligned at the right side of the cell can be recognized better. Because the text before the number is translated the number of spaces at the beginning of the cell is reduced to one space and the alignment gets broken.

May be you find an easy way to fix this.

Thanx

**Comment by NetaliDev** [comment]
I know about this bug and it exists because the DeepL-API does very strange things to the DokuWiki-Syntax. I have already fixed this for the alignment of media embeds, but it is much more difficult to do this for tables, because I have to detect that this is a table and then I have to extract the alignment of the current cell and preserve it from modifications through the API (and all of this has to be done in one big regex-replace).

It is on my TODO-List and I try to fix it when I have time for it.

**Comment by extrasec** [comment]
I understand this is difficult and because of minor relevance will not be fixed soon. That is OK. Thank you for your reply.

**Comment by extrasec** [comment]
I could not resist.
The following worked fine for me, you may try to check and use this (not elegant but seams to work):

        // prevent deepl from messing with tables
        $text = str_replace("  ^  ", "<ignore>  ^  </ignore>", $text);
        $text = str_replace("  ^ ", "<ignore>  ^ </ignore>", $text);
        $text = str_replace(" ^  ", "<ignore> ^  </ignore>", $text);
        $text = str_replace("^  ", "<ignore>^  </ignore>", $text);
        $text = str_replace("  ^", "<ignore>  ^</ignore>", $text);
        $text = str_replace("^", "<ignore>^</ignore>", $text);
        $text = str_replace("  |  ", "<ignore>  |  </ignore>", $text);
        $text = str_replace("  | ", "<ignore>  | </ignore>", $text);
        $text = str_replace(" |  ", "<ignore> |  </ignore>", $text);
        $text = str_replace("|  ", "<ignore>|  </ignore>", $text);
        $text = str_replace("  |", "<ignore>  |</ignore>", $text);
        $text = str_replace("|", "<ignore>|</ignore>", $text);

...

        // prevent deepl from messing with tables
        $text = str_replace("<ignore>^</ignore>", "^", $text);
        $text = str_replace("<ignore>^  </ignore>", "^  ", $text);
        $text = str_replace("<ignore>  ^</ignore>", "  ^", $text);
        $text = str_replace("<ignore> ^  </ignore>", " ^  ", $text);
        $text = str_replace("<ignore>  ^ </ignore>", "  ^ ", $text);
        $text = str_replace("<ignore>  ^  </ignore>", "  ^  ", $text);
        $text = str_replace("<ignore>|</ignore>", "|", $text);
        $text = str_replace("<ignore>|  </ignore>", "|  ", $text);
        $text = str_replace("<ignore>  |</ignore>", "  |", $text);
        $text = str_replace("<ignore> |  </ignore>", " |  ", $text);
        $text = str_replace("<ignore>  | </ignore>", "  | ", $text);
        $text = str_replace("<ignore>  |  </ignore>", "  |  ", $text);

**Comment by NetaliDev** [comment]
You can open a pull-request if you want :D

**Comment by extrasec** [comment]
What is a pull-request?

**Comment by NetaliDev** [comment]
GitHub has a nice description: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

But I can also add the fix if you aren't so experienced with git :)

**Comment by extrasec** [comment]
OK, I've learned something about github processes. I just registered yesterday to github to open the issues for your plugin.. Thats a fine function. I love it.
The pull-request is started.  ;-)

**Comment by NetaliDev** [comment]
Yes :D

Just fork the repo, commit your changes and click the open pull request button :)
(but please don't bump the version, I will do this manually)

**Comment by extrasec** [comment]
Thanx again for your great plugin.
Nearly 1000 lines is an impressive work for a plugin.
I am working on an intranet-wiki for a multi-national European IT-Security-Group. They will love the functionallity of your plugin.
Can we do something for you?

**Comment by NetaliDev** [comment]
If you want you can always contribute to the plugin (by opening issues or pull-requests), that would help many people who use the plugin. And there is also a donation-link on the [DokuWiki plugin page](https://www.dokuwiki.org/plugin:deeplautotranslate) :D

PS: I see the changes in your fork but you still have to open the pull-request by pressing the create pull request button :D

**Comment by NetaliDev** [comment]
Closed by #7

**Comment by extrasec** [comment]
BTW: Do you know how to avoid to multiple all acl rules - for every language a separate and fuly rulset? Not easy to administrate.

**Comment by NetaliDev** [comment]
I do this in a unconventional way: I configure and save the ACLs that I want for the default language in the ACL-Editor and then I edit the `conf/acl.auth.php` by hand and copy-paste the ACLs from the original language for all other languages and just add the language namespace to each line.

So I mainly do this by using a text editor and copy-paste :D
