### ISSUE TITLE
Minor Bug: ~~NOCACHE~~ breakes

### ISSUE THREAD

**Issue by extrasec** [NetaliDev/dokuwiki-deepl-autotranslate#6]
Hi,

another minor bug:

If (in my case at the beginning of pages) the "~~NOCACHE~~" is set to avoid errors in pages where a contents change often, this line changes:

"~~NOCACHE~~" changes to "~~NOCACHE~~~"
An additional "~" appeares at the end of the line in the translated page, if language ist "da" but not if language is "en".

"~~NOCACHE~~" changes to "~NOCACHE~~"
The leading "~" is missing in the translated page, if "NOCACHE" is added to the Exclusions. This happens both on pages translated to "en" and pages translated to "da".

Sounds curious but I hope you will see when you try to do it by your own.
It seams to be a bit similar to the bug with the converted double space to single space at the beginning of a cell.
May be both is a parsing problem with calculation the length of a part of text?

Thanx.

**Comment by NetaliDev** [comment]
Aaaand again: DeepL breaks the DokuWiki syntax. But this one is very easy to fix, I will write a fix right now.
